[project]
name = "capteurs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Simon Sassi", email = "ssi63@3ds.com" }
]
requires-python = ">=3.12"
dependencies = [
    "atc-mi-interface>=2.0.0",
]

[project.scripts]
capteurs = "capteurs:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
